### ISSUE TITLE
Add a colored output on Windows?

### ISSUE THREAD

**Issue by alekseysidorov** [bheisler/criterion.rs#267] opened 2019-02-16 12:52 UTC
At the moment criterion output on windows doesn't support colors, thus it is harder to understand benchmark results that on *nix.

**Comment by bheisler** [comment] 2019-02-16 20:22
Hey, thanks for the suggestion! That seems like a reasonable feature to add, but I don't typically develop on Windows. Pull requests would be welcome, though!

**Comment by vpetrigo** [comment] 2019-02-26 21:38
Hey @alekseysidorov,

Would you please specify which Windows version you mean? I'm on Windows 10 (build 1809 - 10.0.17763) and color output works fine for me.

So that's is the short snippet I added into the `report.rs`:

```rust
    #[test]
    fn test_windows_colors() {
        let cli = CliReport::new(false, true, false);
        let hello = "Hello";

        println!("{}", cli.green(hello.to_string()));
        println!("{}", cli.red(hello.to_string()));
    }
```

And how it looks in the plain `cmd`:

![Hello Test](https://i.ibb.co/GxzhzZ0/image.png)

That's how the benchmarks output of `criterion.rs` itself looks like in my `cmd`:

![Criterion Bench](https://i.ibb.co/tXSR9Lf/image.png)

I may elaborate on that, but need more info about the system you experienced such an issue. 😄

**Comment by vpetrigo** [comment] 2019-02-27 18:49
Small update on that: seems like that issue with lack of colors in Windows terminals has been fixed in rust-lang/cargo#4722. So I was able to reproduce OP's issue with Rust 1.26.0, but it went away after I switched back to the `stable-msvc` toolchain.

**Comment by alekseysidorov** [comment] 2019-03-01 06:44
I am using rustc version `1.32.0` and `powershell` as shell. Sometimes I run tests in `git-bash` but I never tried to run criterion benchmarks in `cmd.exe`.

**Comment by vpetrigo** [comment] 2019-03-01 07:29
@alekseysidorov try to run you benchmarks with the following command: `cargo bench -- --color=always`. I guess there are some issues with traking PowerShell color output features.

**Comment by alekseysidorov** [comment] 2019-03-01 09:18
With additional argument works fine in powershell
![2019-03-01_12-14-14](https://user-images.githubusercontent.com/83360/53628343-deb99a80-3c1b-11e9-82f5-8c636be3f9ff.png)
But without them colors do not work:
`cmd.exe`
![2019-03-01_09-58-03](https://user-images.githubusercontent.com/83360/53628403-01e44a00-3c1c-11e9-91c4-14bd59e54ed5.png)
`powershell`
![2019-03-01_09-58-22](https://user-images.githubusercontent.com/83360/53628474-2a6c4400-3c1c-11e9-932d-b03f6aca74b4.png)

**Comment by vpetrigo** [comment] 2019-03-01 09:46
Would you specify which OS version you use and Criterion.rc?

**Comment by vpetrigo** [comment] 2019-03-01 11:23
@alekseysidorov @bheisler I found potential fix, so will work on a PR.

**Comment by alekseysidorov** [comment] 2019-03-02 18:30
Sorry for delay ^_^, my OS is Windows 10  release 1809 (17763.316)

**Comment by alekseysidorov** [comment] 2019-03-02 19:15
And I used a master branch of `criterion-rs`.

**Comment by bheisler** [comment] 2019-03-05 14:32
Hey, thanks for the patience - I've been on vacation for a week and a half or so.

This fix looks good to me. @alekseysidorov Does this solve the issue for you?

**Comment by bheisler** [comment] 2019-06-16 13:47
Closing this; it seems to be fixed.

**Closed as completed by bheisler** 2019-06-16 13:47 UTC
Labels: Enhancement, Beginner
