### ISSUE TITLE
Benchmark scalability for multiple cores?

### ISSUE THREAD

**Issue by jbreitbart** [bheisler/criterion.rs#265] opened 2019-02-02 12:06 UTC
I am wondering what is the best approach to do not only check the runtime of a function, but also check its scalability when used by multiple threads. For example, it may be interesting to check the performance of having multiple threads add an element to a hashmap or make sure that my latests changes do not break the scalability of an algorithm.

Is using `bench_function_over_inputs` and pass the number of threads as a parameter the correct approach?

**Comment by bheisler** [comment] 2019-02-02 13:38
Hey, thanks for trying Criterion.rs!

Passing the number of threads as a parameter is one reasonable way to do it. It does mean you can't (easily) pass other things as the parameter, though. I would recommend using multiple "functions" where each function is the same function with a different number of threads.

Unfortunately, I think you'll have to manually iterate your code inside each thread in order to create thread contention. That will make the measurements harder for Criterion.rs to analyze and harder for the reader to understand, which is not great.

I think your use case calls for a `bencher.iter_custom(|iters: usize| {...} -> Duration)` function. If that were available, you could spin up your threads and signal them to each run `iters` iterations of the hashmap insertion or whatever. You would have to write your own timing measurements (by which I mean use `Instant::now()` and `Instant::elapsed()`) but it would get you much better measurements.

**Comment by jbreitbart** [comment] 2019-02-10 14:07
Thanks for the quick reply (and sorry for me being slow, I don't have much time to work on my rust stuff). I general, I think it would be great if there were explicit support for multi-threaded measurements and analysis. Here is some feedback / questions on your suggestions.

Having one benchmark functions per thread count makes it hard to benchmark on machines with different number of cores, which is why I have moved forward with the idea of passing the thread count as a parameter. It is not great, especially as I am also benchmarking thread creation in my current code.

I am not sure how it would look like if there would be a `bencher.iter_custom(|iters: usize| {...} -> Duration)` function. Would I just do the time measurements on my own or would I also have to do the analysis? Doing the measurements seems to be fairly easy, but I think doing the analysis should be in a library as one can easily make a mistake there. There are also quite a lot of analysis that could make sense depending on test case.

Would support for rayon be easier than support for multiple threads in general?

**Comment by bheisler** [comment] 2019-02-16 17:52
> I am not sure how it would look like if there would be a `bencher.iter_custom(|iters: usize| {...} -> Duration)` function. Would I just do the time measurements on my own or would I also have to do the analysis?

Your code would simply do the measurement; Criterion.rs will take care of the analysis.

> Would support for rayon be easier than support for multiple threads in general?

Well, the problem isn't so much with supporting threads. It's more that what you want to do doesn't fit easily into the existing timing models. Criterion.rs expects to simply call a function many times and measure how long that took. If the function uses Rayon behind the scenes, that's no problem. In a threaded context, each iteration of the benchmark means starting a thread, calling a function once and joining the thread (or in the case of Rayon, submitting a job that calls the function once and then waiting for the job to complete). This means that the overhead of starting the thread/submitting the job is likely going to outweigh the actual runtime of the function, and it will make it very difficult to measure any actual thread contention. You could mitigate that by artificially increasing the work done by the thread but that sucks.

What you want to do is start up some number of threads and have them wait for some signal, then all start concurrently accessing a shared data structure at once, measuring the time until they all complete some number of accesses. That way, you could see how the number of threads affects the overall runtime. That's not really all that hard to do, but it is a very niche use case and I'm reluctant to add that code directly to Criterion.rs itself. Thus, it seems like a good solution would be to allow you (and others with niche use cases) to plug custom timing loops into Criterion.rs.

**Comment by bheisler** [comment] 2019-08-25 16:02
This should be possible to implement now in 0.3.0 with the `iter_custom` timing loop. I'm going to close this for now; please re-open if that doesn't suit your needs.

**Closed as completed by bheisler** 2019-08-25 16:02 UTC
Labels: Enhancement, Beginner
