### ISSUE TITLE
Expose benchmark result through API?

### ISSUE THREAD

**Issue by marcusklaas** [bheisler/criterion.rs#289] opened 2019-04-26 10:12 UTC
I'm trying to add a performance test to a crate to ensure a certain operation scales subquadratically by comparing benchmark results for different sized inputs. Unfortunately, it looks like it's not possible access the iteration time estimate like it is in the [standard Bencher](https://docs.rs/bencher/0.1.5/bencher/struct.Bencher.html#method.ns_per_iter). Would it be sensible to add something similar to Criterion?

**Comment by bheisler** [comment] 2019-05-07 00:30
Hey, thanks for the suggestion, and thanks for trying Criterion.rs!

Yeah, that's one of the oldest feature requests (see #73) - since before I took over the project, in fact. It's still kicking around the to-do list, but it's never really been a priority and I haven't had a lot of time to work on Criterion.rs lately. Sorry that this probably doesn't help much.

**Comment by bheisler** [comment] 2019-06-08 16:18
Closing as duplicate of #73.

**Closed as completed by bheisler** 2019-06-08 16:18 UTC
